import Head from "next/head";
import CircleBackground from "../Layout/CircleBackground/CircleBackground";
import Footer from "../Layout/Footer/Footer";
import Navbar from "../Layout/Navbar/Navbar";
import Member from "../components/About/Member";
import Vision from "../components/About/Vision";

const about = () => {
  return (
    <>
      <Head>
        <title>Frontend Mentor - PayAPI - About</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link
          rel="icon"
          type="image/png"
          sizes="32x32"
          href="./assets/favicon-32x32.png"
        />
      </Head>
      <main className="">
        <div className="overflow-hidden relative ">
          <Navbar />
          <div className="w-[780px] h-[780px] bg-sanJuanBlue opacity-[.2] rounded-full absolute left-[74px] top-[-634px] sm:left-[440px] sm:top-[-550px] lg:left-[800px]"></div>
          <main className="overflow-hidden max-w-[1440px] mx-auto">
            <Member />
            <Vision />
          </main>
        </div>
        <Footer />
      </main>
    </>
  );
};
export default about;
