import Head from "next/head";
import Image from "next/image";
import React from "react";
import circle from "../../public/assets/shared/desktop/bg-pattern-circle.svg";
import Member from "../components/About/Member";
import Contact from "../components/Contact/Contact";
import ContactForm from "../components/Contact/ContactForm";
import InnovatorsList from "../components/Contact/InnovatorsList";
import Pricing from "../components/Pricing/Pricing";
import Footer from "../Layout/Footer/Footer";
import Navbar from "../Layout/Navbar/Navbar";

type contactProps = {};

const contact: React.FC<contactProps> = () => {
  return (
    <>
      <Head>
        <title>Frontend Mentor - PayAPI - Contact</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link
          rel="icon"
          type="image/png"
          sizes="32x32"
          href="./assets/favicon-32x32.png"
        />
      </Head>
      <div className="">
        <div className="max-w-[1400px] mx-auto overflow-hidden relative lg:px-20">
          <Navbar />
          <div className="w-[780px] h-[780px] bg-sanJuanBlue opacity-[.2] rounded-full absolute left-[74px] top-[-634px] sm:left-[440px] sm:top-[-550px] lg:left-[800px]"></div>
          <main>
            <Contact />
          </main>
        </div>
        <Footer />
      </div>
    </>
  );
};
export default contact;
