import Head from "next/head";
import CircleBackground from "../Layout/CircleBackground/CircleBackground";
import Footer from "../Layout/Footer/Footer";
import Navbar from "../Layout/Navbar/Navbar";
import Hero from "../components/Home/Hero";
import Implement from "../components/Home/Implement";
import Work from "../components/Home/Work";

export default function Home() {
  return (
    <>
      <Head>
        <title>Frontend Mentor - PayAPI - Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link
          rel="icon"
          type="image/png"
          sizes="32x32"
          href="./assets/favicon-32x32.png"
        />
      </Head>
      <div className="overflow-hidden relative max-w-[1440px] mx-auto">
        <Navbar />
        <CircleBackground
          cssClasses="-z-[1] w-[780px] h-[780px] top-[-525px]
           sm:w-[949px] sm:h-[949px] sm:top-[-700px] lg:top-[-320px] lg:left-[700px]"
          circleSection="home"
        />
        <Hero />
      </div>
      <main className="">
        <Work />
        <Implement />
      </main>
      <Footer />
    </>
  );
}
