import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import circle from "../../public/assets/shared/desktop/bg-pattern-circle.svg";
import Navbar from "../Layout/Navbar/Navbar";
import Hero from "../components/Home/Hero";
import Work from "../components/Home/Work";
import Implement from "../components/Home/Implement";
import Footer from "../Layout/Footer/Footer";

// const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Frontend Mentor - PayAPI - Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link
          rel="icon"
          type="image/png"
          sizes="32x32"
          href="./assets/favicon-32x32.png"
        />
      </Head>
      <div className="max-w-[1400px] mx-auto overflow-hidden bg">
        <Navbar />
        <Image
          src={circle}
          alt=""
          className="absolute w-[780px] h-[780px] sm:w-[949px] sm:h-[949px] lg:w-[780px] lg:h-[780px] object-none top-[-540px] -z-10 lg:left-[650px] lg:top-[-250px] "
        />
        <Hero />
      </div>
      <main className="">
        <Work />
        <Implement />
        <Footer />
      </main>
    </>
  );
}
