import Head from "next/head";
import React from "react";
import Image from "next/image";
import circle from "../../public/assets/shared/desktop/bg-pattern-circle.svg";
import Hero from "../components/Home/Hero";
import Implement from "../components/Home/Implement";
import Work from "../components/Home/Work";
import Pricing from "../components/Pricing/Pricing";
import Footer from "../Layout/Footer/Footer";
import Navbar from "../Layout/Navbar/Navbar";

type pricingProps = {};

const pricing: React.FC<pricingProps> = () => {
  return (
    <>
      <Head>
        <title>Frontend Mentor - PayAPI - Pricing</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link
          rel="icon"
          type="image/png"
          sizes="32x32"
          href="./assets/favicon-32x32.png"
        />
      </Head>
      <div className="max-w-[1400px] mx-auto overflow-hidden bg">
        <Navbar />
        <Image
          src={circle}
          alt=""
          className="absolute w-[780px] h-[780px] sm:w-[949px] sm:h-[949px] lg:w-[780px] lg:h-[780px]  
          top-[-644px] -right-[200px] -z-10 lg:left-[650px] lg:top-[-250px] "
        />

        <main className="">
          <Pricing />
          {/* <Work />
        <Implement />
        <Footer /> */}
        </main>
      </div>
    </>
  );
};
export default pricing;
